[book]
authors = ["jason-bowen-zheng"]
language = "zh"
multilingual = false
src = "src"
title = "中文文档"

[output.html]
curly-quotes = true
mathjax-support = false
additional-js = ["src/js/mermaid.min.js", "src/js/mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
