site_name: Minecraft in python

nav:
  - Home: index.md
  - Launcher: launcher.md
  - Install game: install-game.md
  - Resource pack: resource-pack.md
  - About:
    - Contributing: about/contributing.md
    - License: about/license.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - bash
    - javascript
    - python

copyright: Copyright &copy 2020-2021 Minecraft-in-python<br>&nbsp;&nbsp;All Right Reserved.

markdown_extensions:
  - admonition
  - pymdownx.details
